import { LoginUserUseCase } from '@/@core/application/user/login.use-case'
import { PingUseCase } from '@/@core/application/user/ping.use-case'
import { Registry, container } from '@/@core/infra/container-registry'
import Head from 'next/head'

export default function Home() {

    const useCase = container.get<PingUseCase>(Registry.PingUseCase)
    useCase.execute()

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>

            </main>
        </>
    )
}