version: '3'

services:
    ai:
        container_name: ai
        build:
            context: ./ai
            dockerfile: Dockerfile
        volumes:
          - ./ai/:/app/
        ports:
            - 5000:5000
        depends_on:
            - postgresqldb
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: dev.Dockerfile
        ports:
            - 4000:4000
        depends_on:
            - postgresqldb
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: dev.Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - backend
            - ai
    postgresqldb:
        container_name: pg
        image: postgres:15-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=123456
            - POSTGRES_USER=fullzer4
            - POSTGRES_DB=acustticai
        networks:
            - dev-network

networks:
    dev-network:
        external: true