version: '3'

services:
    postgresqldb:
        image: postgres:15-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=123456
            - POSTGRES_USER=fullzer4
            - POSTGRES_DB=acustticai
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "gabrielpelizzaro@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "123456"
        ports:
            - "16543:80"