services:
  trafficAI:
    image: ./trafficAI
    ports:
      - 50051:50051
  noiseAI:
    image: ./noiseAI
    ports:
      - 50052:50052
  auth:
    image: ./auth
    ports:
      - 50053:50053
  gateway:
    image: ./gateway
    ports:
      - 50050:50050