version: '3'

services:
  backend:
    build:
      context: ./Backend  
      dockerfile: Dockerfile  
    ports:
      - "4000:4000"
    networks:
      - compose-network
    volumes:
      - ./Backend:/app
  frontend:
    build:
      context: ./Frontend  
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"
    networks:
      - compose-network
    volumes:
      - ./Frontend:/app  

networks: 
  compose-network:
    driver: bridge