version: '3'

services:
    postgresqldb:
        container_name: pg
        image: postgres:15-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_NAME}
        networks:
            - prod-network
    nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: prod.Dockerfile
    ai:
        container_name: ai
        build:
            context: ./ai
            dockerfile: prod.Dockerfile
        environment:
            JWT_key: ${JWT_key}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - 5000:5000
        networks:
            - prod-network
        links:
            - postgresqldb
        depends_on:
            - postgresqldb
    backend:
        image: backend
        build:
            context: ./backend
            dockerfile: prod.Dockerfile
        environment:
            JWT_key: ${JWT_key}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - 4000:4000
        networks:
            - prod-network
        links:
            - postgresqldb
        depends_on:
            - postgresqldb
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: prod.Dockerfile
        environment:
            JWT_key: ${JWT_key}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3000:3000
        networks:
            - prod-network
        links:
            - backend
            - ai
        depends_on:
            - backend
            - ai

networks:
    prod-network:
        external: true
        driver: bridge