services:
  redis:
    image: redis
    command: redis-server --requirepass TesteLocal!
    ports:
      - "6379:6379"
    networks:
      - network
  gateway:
    image: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - network
  trafficai:
    image: trafficai
    build:
      context: ./trafficAI
      dockerfile: Dockerfile
    ports:
      - 8070:8070
    networks:
      - network
  website:
    image: website
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - network

networks: 
  network:
    driver: bridge