version: '3'

services:
    nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
    ai:
        container_name: ai
        build:
            context: ./ai
            dockerfile: Dockerfile
        volumes:
          - ./ai/:/app/
        environment:
            JWT_key: ${JWT_key}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - 5000:5000
        networks:
            - dev-network
        depends_on:
            - postgresqldb
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: dev.Dockerfile
        volumes:
          - ./backend/:/app/
        environment:
            JWT_key: ${JWT_key}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - 4000:4000
        networks:
            - dev-network
        depends_on:
            - postgresqldb
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: dev.Dockerfile
        volumes:
          - ./frontend/src:/app/src
          - ./frontend/public:/app/public
        environment:
            JWT_key: ${JWT_key}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3000:3000
        networks:
            - dev-network
        depends_on:
            - backend
            - ai
    postgresqldb:
        container_name: pg
        image: postgres:15-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_NAME}
        networks:
            - dev-network

networks:
    dev-network:
        external: true