services:
  trafficai:
    image: trafficai
    build:
      context: ./trafficAI
      dockerfile: Dockerfile
    ports:
      - 50051:50051
  noiseai:
    image: noiseai
    build:
      context: ./noiseAI
      dockerfile: Dockerfile
    ports:
      - 50052:50052
  gateway:
    image: gatewaygql
    build:
      context: ./gatewayGQL
      dockerfile: Dockerfile
    ports:
      - 50050:50050