apiVersion: apps/v1
kind: Deployment
metadata:
  name: acustticai-ais-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: acustticai-ais
  template:
    metadata:
      labels:
        app: acustticai-ais
    spec:
      containers:
      - name: acustticai-ais
        image: fullzer4/acustticai-ais:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
