# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\ttrafficAI\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x1d\n\nImageReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0cVideoRequest\x12\r\n\x05video\x18\x01 \x01(\x0c\"\x1d\n\nVideoReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xc5\x01\n\x07Greeter\x12<\n\x08sayHello\x12\x17.trafficAI.HelloRequest\x1a\x15.trafficAI.HelloReply\"\x00\x12=\n\tsendImage\x12\x17.trafficAI.ImageRequest\x1a\x15.trafficAI.ImageReply\"\x00\x12=\n\tsendVideo\x12\x17.trafficAI.VideoRequest\x1a\x15.trafficAI.VideoReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=24
  _HELLOREQUEST._serialized_end=52
  _HELLOREPLY._serialized_start=54
  _HELLOREPLY._serialized_end=83
  _IMAGEREQUEST._serialized_start=85
  _IMAGEREQUEST._serialized_end=114
  _IMAGEREPLY._serialized_start=116
  _IMAGEREPLY._serialized_end=145
  _VIDEOREQUEST._serialized_start=147
  _VIDEOREQUEST._serialized_end=176
  _VIDEOREPLY._serialized_start=178
  _VIDEOREPLY._serialized_end=207
  _GREETER._serialized_start=210
  _GREETER._serialized_end=407
# @@protoc_insertion_point(module_scope)
