# sayHello function from trafficAI

mutation Hello($name: String!) {
  sayHello(name: $name) {
    message
  }
}

mutation CreateUser($username: String, $email: String, $password: String) {
  createUser(username: $username, email: $email, password: $password) {
    message
  }
}