name: Node.js tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start Docker Compose
      run: docker-compose -f docker-compose.dev.yml up -d

    - name: Setup .env variables
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_NAME: acustticai
        DB_USERNAME: fullzer4
        DB_PASSWORD: 123456
      run: |
        echo $DB_HOST

    - name: Install dependencies and run tests
      run: |
        cd backend
        yarn
        yarn test