name: Node.js tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: docker-compose -f docker-compose.dev.yml up -d
    - name: Setup .env variables
        env:
          DB_HOST: ${{ DATABASEHOSTTEST }}
          DB_PORT: ${{ DATABASEPORTTEST }}
          DB_NAME: ${{ DATABASENAMETEST }}
          DB_USERNAME: ${{ DATABASEUSERTEST }}
          DB_PASSWORD: ${{ DATABASEPASSWORDTEST }}
        run: |
          echo $DB_HOST
    - run: cd backend && yarn
    - run: cd backend && yarn test