name: Deploy
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: ["python-ai.yml", "nextjs.yml", "backend.yml", "docker-images.yml", "integration.yml"]
    types:
      - completed
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy files
        run: |
          lftp -c "open -u ${{ secrets.SFTP_USERNAME }},${{ secrets.SFTP_PASSWORD }} sftp://${{ secrets.SFTP_SERVER }}:2222 && mirror -R --exclude-glob .git/ --exclude .github/ --exclude .gitignore --exclude README.md ./ remote/path"  
