name: Deploy
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: ["python-ai.yml", "nextjs.yml", "backend.yml", "docker-images.yml", "integration.yml"]
    types:
      - completed
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
     - name: Checkout
       uses: actions/checkout@v2.3.4
     - name: Upload Files
       id: upload
       uses: Creepios/sftp-action@v1.0.3
       with:
         host: ${{ secrets.SFTP_SERVER }}
         port: 2222
         username: ${{ secrets.SFTP_USERNAME }}
         password: ${{ secrets.SFTP_PASSWORD }}
         localPath: './frontend/'
         remotePath: './'
