name: Deploy
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: ["python-ai.yml", "nextjs.yml", "backend.yml", "docker-images.yml", "integration.yml"]
    types:
      - completed
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
            username: ${{ secrets.SFTP_USERNAME }}
            server: ${{ secrets.SFTP_SERVER }}
            port: ${{ secrets.STFP_PORT }}
            ssh_private_key: ${{ secrets.STFP_SSH_KEY }}
            local_path: './*'
            remote_path: '/var/www'
            sftp_only: true
