name: Integration tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

  strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: iniciar todos os servicos
      run: docker-compose -f docker-compose.yml up -d
    - name: rodar test de integracao
    - run: |
      cd .github/integration_test/
      yarn build
      node dist/main.js