name: Load balance tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Cache Yarn dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('.github/integration_test/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start all services
      run: docker-compose -f docker-compose.yml up -d
    - name: Run integration tests
      run: |
        cd .github/integration_test/
        yarn
        yarn build
        node dist/main.js